find_package(Threads REQUIRED)

if(VISIONARM_ENABLE_FFMPEG_AUDIO_ENCODER)
    set(FFMPEG_INCLUDE_DIR "" CACHE PATH
        "Directory containing libavcodec/avcodec.h and libavutil headers")
    set(FFMPEG_AVCODEC_LIBRARY "" CACHE FILEPATH "Full path to libavcodec.so")
    set(FFMPEG_AVUTIL_LIBRARY "" CACHE FILEPATH "Full path to libavutil.so")
    if(NOT FFMPEG_INCLUDE_DIR)
        find_path(FFMPEG_INCLUDE_DIR NAMES libavcodec/avcodec.h)
    endif()
    if(NOT FFMPEG_AVCODEC_LIBRARY)
        find_library(FFMPEG_AVCODEC_LIBRARY NAMES avcodec)
    endif()
    if(NOT FFMPEG_AVUTIL_LIBRARY)
        find_library(FFMPEG_AVUTIL_LIBRARY NAMES avutil)
    endif()
    if(NOT FFMPEG_INCLUDE_DIR OR NOT FFMPEG_AVCODEC_LIBRARY OR NOT FFMPEG_AVUTIL_LIBRARY)
        message(FATAL_ERROR
            "VISIONARM_ENABLE_FFMPEG_AUDIO_ENCODER=ON requires FFmpeg libavcodec/libavutil development files. "
            "Set FFMPEG_INCLUDE_DIR, FFMPEG_AVCODEC_LIBRARY, and FFMPEG_AVUTIL_LIBRARY if CMake cannot find the Buildroot staging files.")
    endif()
endif()

if(VISIONARM_ENABLE_FFMPEG_MP4_MUX OR VISIONARM_ENABLE_FFMPEG_MPEGTS_NETWORK)
    set(FFMPEG_AVFORMAT_LIBRARY "" CACHE FILEPATH "Full path to libavformat.so")
    if(NOT FFMPEG_AVFORMAT_LIBRARY)
        find_library(FFMPEG_AVFORMAT_LIBRARY NAMES avformat)
    endif()
    if(NOT FFMPEG_AVFORMAT_LIBRARY)
        message(FATAL_ERROR "FFmpeg MP4/MPEG-TS output requires libavformat. Set FFMPEG_AVFORMAT_LIBRARY to the Buildroot staging libavformat.so")
    endif()
endif()

if(VISIONARM_ENABLE_ALSA_AUDIO)
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(ALSA QUIET IMPORTED_TARGET alsa)
    endif()
    if(NOT TARGET PkgConfig::ALSA)
        find_path(ALSA_INCLUDE_DIR NAMES alsa/asoundlib.h)
        find_library(ALSA_LIBRARY NAMES asound)
        if(NOT ALSA_INCLUDE_DIR OR NOT ALSA_LIBRARY)
            message(FATAL_ERROR "VISIONARM_ENABLE_ALSA_AUDIO=ON but alsa-lib development files were not found")
        endif()
    endif()
endif()

if(VISIONARM_BUILD_RUNTIME)
    set(RKNN_INCLUDE_DIR "" CACHE PATH "Directory containing rknn_api.h")
    set(RKNN_LIBRARY "" CACHE FILEPATH
        "Full path to librknnrt.so or the platform RKNN runtime library")
    if(NOT RKNN_INCLUDE_DIR)
        message(FATAL_ERROR "Set RKNN_INCLUDE_DIR to the directory containing rknn_api.h")
    endif()
    if(NOT RKNN_LIBRARY)
        message(FATAL_ERROR "Set RKNN_LIBRARY to the RKNN runtime library")
    endif()
    if(VISIONARM_ENABLE_OPENCV_PREPROCESS)
        find_package(OpenCV REQUIRED COMPONENTS core imgproc)
    endif()
    if(VISIONARM_ENABLE_RGA_PREPROCESS)
        set(RGA_INCLUDE_DIR "" CACHE PATH "Directory containing im2d.hpp")
        set(RGA_LIBRARY "" CACHE FILEPATH "Full path to librga.so")
        if(NOT RGA_INCLUDE_DIR)
            message(FATAL_ERROR "Set RGA_INCLUDE_DIR to the directory containing im2d.hpp")
        endif()
        if(NOT RGA_LIBRARY)
            message(FATAL_ERROR "Set RGA_LIBRARY to librga.so")
        endif()
    endif()
    if(VISIONARM_ENABLE_MPP_VIDEO)
        set(MPP_INCLUDE_DIR "" CACHE PATH "Directory containing rk_mpi.h and mpp_buffer.h")
        set(MPP_LIBRARY "" CACHE FILEPATH "Full path to librockchip_mpp.so")
        if(NOT MPP_INCLUDE_DIR)
            message(FATAL_ERROR "Set MPP_INCLUDE_DIR to the Rockchip MPP include directory")
        endif()
        if(NOT MPP_LIBRARY)
            message(FATAL_ERROR "Set MPP_LIBRARY to librockchip_mpp.so")
        endif()
    endif()
endif()
