set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TOOLCHAIN_ROOT
    "/opt/atk-dlrk3588-toolchain")

set(TOOLCHAIN_BIN
    "${TOOLCHAIN_ROOT}/bin")

set(CMAKE_C_COMPILER
    "${TOOLCHAIN_BIN}/aarch64-buildroot-linux-gnu-gcc")

set(CMAKE_CXX_COMPILER
    "${TOOLCHAIN_BIN}/aarch64-buildroot-linux-gnu-g++")


execute_process(
    COMMAND
        ${CMAKE_C_COMPILER} -print-sysroot
    OUTPUT_VARIABLE
        CMAKE_SYSROOT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)


set(CMAKE_FIND_ROOT_PATH
    ${CMAKE_SYSROOT}
)


set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)